name: metadata_fetch_plus
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, Twitter Cards, and Structured Data (Json-LD)
version: 1.0.0
homepage: https://github.com/nghiashiyi/metadata_fetch
publish_to: https://pub.dev/

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  http: ^1.1.0
  string_validator: ^1.0.0
  html: ^0.15.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.24.6
